- hosts: all
  become: yes
  roles:
    - kubernetes
    - kubelet
    - kubeadm
    - containerd
 
- hosts: master
  become: yes
  roles:
    - control-plane
    
- hosts: workers
  become: yes
  roles:
    - worker